package events

import (
	"fmt"
	"strings"
)

// The event catalog. Every event iPulse can emit is registered here with its
// severity, trigger condition, documented fields and suggested operator action.
// docs/event-catalog.md is generated from this data (`ipulse events catalog --markdown`).
func init() {
	register(
		// ---------------------------------------------------------------- 1000-1999
		Definition{SpeedTestStarted, "SPEED_TEST_STARTED", Debug, CatConnectivity,
			"A speed test has begun.",
			"Scheduled full or lightweight speed test, or a manual test request.",
			[]string{"Mode", "Provider", "TestServer"},
			"None. Informational."},
		Definition{SpeedTestCompleted, "SPEED_TEST_COMPLETED", Info, CatConnectivity,
			"A speed test finished successfully.",
			"Completion of a scheduled or manual speed test.",
			[]string{"Download", "Upload", "Latency", "Jitter", "PacketLoss", "Status", "TestServer", "Duration", "Mode", "BytesDown", "BytesUp", "Streams"},
			"None. This is the primary performance record."},
		Definition{SpeedTestFailed, "SPEED_TEST_FAILED", Warning, CatConnectivity,
			"A speed test could not be completed.",
			"All configured endpoints failed, or the test was aborted by loss of connectivity.",
			[]string{"Mode", "Provider", "TestServer", "Error", "Attempts"},
			"Check Internet connectivity and the configured speed_test endpoints."},
		Definition{ThroughputSample, "THROUGHPUT_SAMPLE", Debug, CatConnectivity,
			"A lightweight throughput probe completed.",
			"The lightweight throughput interval elapsed.",
			[]string{"Download", "Latency", "Bytes", "Duration", "TestServer"},
			"None. Feeds baselines between full tests."},
		Definition{ConnectivityCheckOK, "CONNECTIVITY_CHECK_OK", Debug, CatConnectivity,
			"A periodic health check succeeded.",
			"The basic health interval elapsed and at least the required number of targets responded.",
			[]string{"Targets", "Succeeded", "RTT", "Method"},
			"None."},
		Definition{ConnectivityCheckFailed, "CONNECTIVITY_CHECK_FAILED", Warning, CatConnectivity,
			"A periodic health check failed; diagnostics will run.",
			"Fewer than the required number of health targets responded.",
			[]string{"Targets", "Succeeded", "Failures", "Method"},
			"None required; iPulse escalates to layered diagnostics automatically."},
		Definition{InternetRestored, "INTERNET_CONNECTIVITY_RESTORED", Notice, CatConnectivity,
			"Internet connectivity returned after a failure.",
			"A health check succeeded while an outage was open.",
			[]string{"OutageDuration", "PreviousCause", "Targets"},
			"Review the closed outage record for the probable cause."},
		Definition{HealthScoreUpdated, "HEALTH_SCORE_UPDATED", Debug, CatConnectivity,
			"The Internet health score was recomputed.",
			"The health score interval elapsed.",
			[]string{"Score", "Availability", "Download", "Upload", "Latency", "Jitter", "PacketLoss", "DNS"},
			"None."},
		Definition{HealthScoreDegraded, "HEALTH_SCORE_DEGRADED", Warning, CatConnectivity,
			"The Internet health score dropped below the configured threshold.",
			"Score fell under health.warn_below for the configured persistence.",
			[]string{"Score", "Threshold", "WorstComponent", "ComponentScores"},
			"Inspect the named worst component on the dashboard."},
		Definition{SpeedEndpointUnavailable, "SPEED_TEST_ENDPOINT_UNAVAILABLE", Notice, CatConnectivity,
			"A configured speed-test endpoint could not be used.",
			"Endpoint selection failed for one endpoint while others remain usable.",
			[]string{"Endpoint", "Error"},
			"Remove or replace the endpoint if the failure persists."},
		Definition{SpeedTestSkippedBusy, "SPEED_TEST_SKIPPED", Notice, CatConnectivity,
			"A scheduled speed test was skipped.",
			"The link was already saturated by other traffic, or connectivity was down, or a test was already running.",
			[]string{"Reason", "Mode", "ObservedMbps"},
			"None. Skipping avoids both wasted bandwidth and misleading results."},

		// ---------------------------------------------------------------- 2000-2999
		Definition{DownloadDegradation, "DOWNLOAD_DEGRADATION", Warning, CatPerformance,
			"Measured download throughput is substantially below its baseline.",
			"Download fell more than alerts.download_degradation_percent below the time-aware baseline, for the required persistence.",
			[]string{"BaselineDownload", "CurrentDownload", "Deviation", "Bucket", "Observations", "ProbableCause"},
			"Compare with upload utilisation and latency; if the link is idle, contact the ISP."},
		Definition{UploadDegradation, "UPLOAD_DEGRADATION", Warning, CatPerformance,
			"Measured upload throughput is substantially below its baseline.",
			"Upload fell more than alerts.upload_degradation_percent below the time-aware baseline.",
			[]string{"BaselineUpload", "CurrentUpload", "Deviation", "Bucket", "Observations", "ProbableCause"},
			"Check for local upload saturation before escalating to the ISP."},
		Definition{DownloadBelowISPExpected, "DOWNLOAD_BELOW_ISP_EXPECTATION", Warning, CatPerformance,
			"Download throughput is below the configured advertised ISP speed.",
			"Download < expected_download_mbps by more than alerts.isp_shortfall_percent.",
			[]string{"ExpectedDownload", "MeasuredDownload", "Shortfall", "TestServer", "SamplesBelow", "SampleWindow"},
			"Collect several samples, then raise with the ISP citing the stored history."},
		Definition{UploadBelowISPExpected, "UPLOAD_BELOW_ISP_EXPECTATION", Warning, CatPerformance,
			"Upload throughput is below the configured advertised ISP speed.",
			"Upload < expected_upload_mbps by more than alerts.isp_shortfall_percent.",
			[]string{"ExpectedUpload", "MeasuredUpload", "Shortfall", "TestServer", "SamplesBelow", "SampleWindow"},
			"As above."},
		Definition{PerformanceRecovered, "PERFORMANCE_RECOVERED", Notice, CatPerformance,
			"A performance degradation cleared.",
			"The offending metric returned within its recovery band for the required persistence.",
			[]string{"Metric", "Current", "Baseline", "DegradedFor", "OriginalEvent"},
			"None."},
		Definition{ThroughputDegradation, "THROUGHPUT_DEGRADATION", Warning, CatPerformance,
			"Lightweight throughput probes are consistently below baseline.",
			"Consecutive lightweight probes below the baseline band between full tests.",
			[]string{"BaselineDownload", "CurrentDownload", "Deviation", "Consecutive"},
			"Wait for the next full speed test to confirm."},
		Definition{LatencySpike, "LATENCY_SPIKE", Notice, CatPerformance,
			"A short-lived latency increase was observed.",
			"A single latency sample exceeded the baseline deviation threshold.",
			[]string{"BaselineLatency", "CurrentLatency", "Deviation", "Target"},
			"None unless it becomes sustained."},
		Definition{SustainedHighLatency, "SUSTAINED_HIGH_LATENCY", Warning, CatPerformance,
			"Latency has stayed above baseline for an extended period.",
			"Latency above threshold for alerts.sustained_latency_seconds.",
			[]string{"BaselineLatency", "CurrentLatency", "Deviation", "Duration", "PacketLoss", "ProbableCause"},
			"Check local saturation, Wi-Fi quality, then the ISP."},
		Definition{JitterDegradation, "JITTER_DEGRADATION", Warning, CatPerformance,
			"Latency variation increased significantly.",
			"Jitter exceeded its baseline by alerts.jitter_degradation_percent.",
			[]string{"BaselineJitter", "CurrentJitter", "Deviation", "PacketLoss", "Target"},
			"Jitter harms real-time traffic; check Wi-Fi and local congestion."},
		Definition{LatencyDegradation, "LATENCY_DEGRADATION", Warning, CatPerformance,
			"Latency degraded relative to the established baseline.",
			"Latency exceeded baseline by alerts.latency_degradation_percent with the required persistence.",
			[]string{"BaselineLatency", "CurrentLatency", "Deviation", "PacketLoss", "UploadUtilization", "DownloadUtilization", "ProbableCause"},
			"Use the ProbableCause field; saturation is the most common cause."},
		Definition{PacketLossDetected, "PACKET_LOSS_DETECTED", Warning, CatPerformance,
			"Packet loss exceeded the configured threshold.",
			"Measured loss above alerts.packet_loss_percent over the probe window.",
			[]string{"PacketLoss", "BaselineLoss", "Sent", "Received", "Target", "Latency"},
			"Sustained loss on the first external hop points at the access link."},
		Definition{PacketLossCleared, "PACKET_LOSS_CLEARED", Notice, CatPerformance,
			"Packet loss returned to normal.",
			"Loss below the recovery threshold for the required persistence.",
			[]string{"PacketLoss", "Duration", "Target"},
			"None."},
		Definition{LocalBandwidthSaturation, "LOCAL_BANDWIDTH_SATURATION", Warning, CatPerformance,
			"Local link saturation is degrading Internet quality.",
			"Correlation rule: bandwidth spike plus latency rise plus loss rise or throughput drop.",
			[]string{"Direction", "Utilization", "BaselineLatency", "CurrentLatency", "PacketLoss", "TopProcess", "Evidence", "ProbableCause"},
			"Identify the named process or device consuming the link."},
		Definition{DNSResponseDegradation, "DNS_RESPONSE_DEGRADATION", Warning, CatPerformance,
			"DNS resolution is measurably slower than baseline.",
			"DNS response time above baseline by the configured percentage.",
			[]string{"BaselineDNS", "CurrentDNS", "Deviation", "Server", "Name"},
			"Try an alternate resolver; slow DNS is often mistaken for slow Internet."},
		Definition{UpstreamDegradation, "UPSTREAM_PERFORMANCE_DEGRADATION", Warning, CatPerformance,
			"Throughput is degraded and the local network is not the cause.",
			"Correlation rule: throughput below baseline or plan, with no local saturation and no wireless degradation.",
			[]string{"CurrentDownload", "CurrentUpload", "Deviation", "Evidence", "ProbableCause"},
			"This is the evidence an ISP ticket needs: the local link was idle and healthy while throughput was low."},
		Definition{RouteLatencyDegradation, "ROUTE_LATENCY_DEGRADATION", Notice, CatPerformance,
			"Per-hop latency on a monitored path increased.",
			"Hop RTT increase beyond threshold on a stable path.",
			[]string{"Destination", "Hop", "HopAddress", "BaselineRTT", "CurrentRTT", "Deviation"},
			"Useful evidence for an ISP ticket; the first degraded hop localises the problem."},

		// ---------------------------------------------------------------- 3000-3999
		Definition{InternetConnectivityLost, "INTERNET_CONNECTIVITY_LOST", Error, CatAvailability,
			"Internet connectivity is unavailable.",
			"Health checks failed and layered diagnostics confirmed loss of Internet reachability.",
			[]string{"GatewayReachable", "DNSReachable", "ExternalIPReachable", "HTTPSReachable", "InterfaceUp", "ProbableCause"},
			"Follow the ProbableCause classification."},
		Definition{OutageStarted, "OUTAGE_STARTED", Error, CatAvailability,
			"An outage record was opened.",
			"Connectivity loss confirmed by diagnostics.",
			[]string{"Classification", "ProbableCause", "Evidence", "Interface", "Gateway"},
			"See the outage view on the dashboard."},
		Definition{OutageEnded, "OUTAGE_ENDED", Notice, CatAvailability,
			"An outage record was closed.",
			"Connectivity was restored.",
			[]string{"Classification", "ProbableCause", "Duration", "Start", "End"},
			"None."},
		Definition{ISPOutage, "ISP_OUTAGE", Error, CatAvailability,
			"The failure is upstream of this network.",
			"Gateway reachable and DNS working, but multiple independent Internet endpoints in different networks are unreachable.",
			[]string{"GatewayReachable", "DNSReachable", "EndpointsTested", "EndpointsReachable", "Evidence"},
			"Report to the ISP; local remediation will not help."},
		Definition{DNSFailure, "DNS_FAILURE", Error, CatAvailability,
			"Name resolution is failing while the network path works.",
			"Gateway reachable and external IP literals reachable, but DNS queries fail.",
			[]string{"ServersTested", "ServersFailed", "NamesTested", "ExternalIPReachable", "Evidence"},
			"Switch resolvers or restart the local resolver service."},
		Definition{GatewayFailure, "GATEWAY_FAILURE", Error, CatAvailability,
			"The default gateway is unreachable.",
			"Interface is up with a valid address, but the gateway does not respond.",
			[]string{"Gateway", "Interface", "InterfaceUp", "LocalIP", "Method", "Evidence"},
			"Check the router/AP and the local link."},
		Definition{LocalInterfaceFailure, "LOCAL_INTERFACE_FAILURE", Critical, CatAvailability,
			"No usable network interface.",
			"No interface is up with a routable address, or the default route is missing.",
			[]string{"Interfaces", "InterfaceUp", "LocalIP", "DefaultRoute", "Evidence"},
			"Check cabling, Wi-Fi association, driver and DHCP."},
		Definition{PartialConnectivity, "PARTIAL_CONNECTIVITY", Warning, CatAvailability,
			"Some Internet destinations are reachable and others are not.",
			"Mixed reachability results across independent endpoints.",
			[]string{"EndpointsTested", "EndpointsReachable", "Unreachable", "Evidence", "ProbableCause"},
			"Often upstream routing or per-protocol filtering; check the unreachable list."},
		Definition{RoutingFailure, "ROUTING_FAILURE", Error, CatAvailability,
			"Traffic is not being routed off the local network.",
			"Gateway reachable but no external destination reachable at IP level, or the default route is invalid.",
			[]string{"DefaultRoute", "Gateway", "Interface", "Evidence", "VPNActive"},
			"Inspect the routing table and any VPN client."},
		Definition{WiFiDegradation, "WIFI_DEGRADATION", Warning, CatAvailability,
			"Wi-Fi quality is degrading connectivity.",
			"Weak RSSI or reduced link rate correlated with loss or latency on the wireless interface.",
			[]string{"SSID", "Signal", "SignalPercent", "LinkSpeed", "Frequency", "Channel", "PacketLoss", "GatewayRTT", "ProbableCause"},
			"Move closer to the AP, change channel, or use a wired link before blaming the ISP."},
		Definition{DiagnosticsCompleted, "DIAGNOSTICS_COMPLETED", Info, CatAvailability,
			"A diagnostic ladder run finished.",
			"Automatic escalation after a failed health check, or a manual diagnostics request.",
			[]string{"Classification", "ProbableCause", "Duration", "Trigger", "Evidence"},
			"None."},
		Definition{AvailabilityReport, "AVAILABILITY_REPORT", Info, CatAvailability,
			"Periodic availability summary.",
			"The availability report interval elapsed.",
			[]string{"Window", "AvailabilityPercent", "Outages", "TotalDowntime", "LongestOutage", "MTBF"},
			"None."},

		// ---------------------------------------------------------------- 4000-4999
		Definition{BandwidthSpikeDownload, "BANDWIDTH_SPIKE_DOWNLOAD", Notice, CatTraffic,
			"Inbound throughput spiked well above its time-aware baseline.",
			"Robust z-score of rx rate exceeded the configured threshold, excluding iPulse's own tests.",
			[]string{"Interface", "CurrentRate", "BaselineRate", "Deviation", "ZScore", "Bucket", "TopProcess"},
			"Correlate with the connections view to identify the source."},
		Definition{BandwidthSpikeUpload, "BANDWIDTH_SPIKE_UPLOAD", Warning, CatTraffic,
			"Outbound throughput spiked well above its time-aware baseline.",
			"Robust z-score of tx rate exceeded the configured threshold, excluding iPulse's own tests.",
			[]string{"Interface", "CurrentRate", "BaselineRate", "Deviation", "ZScore", "Bucket", "TopProcess", "TopDestination"},
			"Outbound spikes deserve attention: identify the process and destination."},
		Definition{SustainedBandwidthUsage, "SUSTAINED_BANDWIDTH_USAGE", Notice, CatTraffic,
			"Elevated throughput persisted for an extended period.",
			"Rate above the baseline band continuously for alerts.sustained_bandwidth_seconds.",
			[]string{"Interface", "Direction", "AverageRate", "PeakRate", "Duration", "BytesTransferred", "TopProcess"},
			"Expected for large downloads/backups; investigate if unexplained."},
		Definition{UnusualOutboundTraffic, "UNUSUAL_OUTBOUND_TRAFFIC", Warning, CatTraffic,
			"Outbound traffic volume is well above the historical pattern for this time.",
			"Upload volume over the window exceeds the time-bucket baseline by the configured factor.",
			[]string{"Interface", "WindowBytes", "BaselineBytes", "Deviation", "Bucket", "TopProcess", "TopDestination", "Confidence"},
			"Metadata only. Verify the responsible process is expected to upload."},
		Definition{SustainedUpload, "SUSTAINED_UPLOAD", Warning, CatTraffic,
			"A sustained outbound transfer is in progress.",
			"Upload rate above the configured floor continuously for alerts.sustained_upload_seconds.",
			[]string{"Interface", "AverageRate", "Duration", "BytesSent", "TopProcess", "TopDestination", "Confidence"},
			"Confirm the transfer is intended (backup, sync, upload)."},
		Definition{LargeOutboundTransfer, "LARGE_OUTBOUND_TRANSFER", Warning, CatTraffic,
			"A single destination received an unusually large outbound volume.",
			"Bytes sent to one destination exceeded alerts.large_transfer_mb within the window.",
			[]string{"Destination", "BytesSent", "Duration", "Process", "RemotePort", "Protocol", "FirstSeen", "Confidence"},
			"Verify the destination and the process. Metadata only; no payload is inspected."},
		Definition{NewHighVolumeDest, "NEW_HIGH_VOLUME_DESTINATION", Warning, CatTraffic,
			"A destination first seen recently is receiving significant outbound traffic.",
			"Destination newer than destinations.new_destination_window with bytes sent above the high-volume floor.",
			[]string{"Destination", "FirstSeen", "BytesSent", "BytesReceived", "Process", "RemotePort", "ASN", "Country", "Confidence"},
			"The combination of new and high-volume is the interesting part; verify it."},
		Definition{UnusualOvernightTraffic, "UNUSUAL_OVERNIGHT_ACTIVITY", Notice, CatTraffic,
			"Significant activity during a normally quiet period.",
			"Traffic during the configured quiet hours exceeded that window's baseline.",
			[]string{"Window", "Direction", "Bytes", "BaselineBytes", "Deviation", "TopProcess", "TopDestination"},
			"Often scheduled updates or backups; confirm once and it becomes the baseline."},
		Definition{PeriodicSpikePattern, "PERIODIC_SPIKE_PATTERN", Info, CatTraffic,
			"Repeating traffic spikes with a regular period were detected.",
			"Autocorrelation of spike timestamps found a dominant period with enough repetitions.",
			[]string{"Period", "Occurrences", "Direction", "AverageSpike", "TopProcess"},
			"Usually a scheduled task; recorded for context, not as a problem."},
		Definition{TrafficBaselineReady, "TRAFFIC_BASELINE_ESTABLISHED", Info, CatTraffic,
			"A traffic baseline reached the minimum observation count and is now active.",
			"Enough samples accumulated for a metric/time bucket.",
			[]string{"Metric", "Bucket", "Observations", "Mean", "Median", "StdDev"},
			"None. Detection for that bucket starts now."},
		Definition{ConnectionCountAnomaly, "CONNECTION_COUNT_ANOMALY", Notice, CatTraffic,
			"The number of active connections deviates strongly from baseline.",
			"Robust z-score of the active connection count exceeded the threshold.",
			[]string{"Current", "BaselineMedian", "ZScore", "Bucket", "TopProcess"},
			"Cross-check the connections and destinations views."},
		Definition{AppUploadAnomaly, "APPLICATION_UPLOAD_ANOMALY", Warning, CatTraffic,
			"One application's upload volume is far above its own history.",
			"Per-process upload volume exceeded that process's baseline by the configured factor.",
			[]string{"Process", "PID", "ExecutablePath", "User", "BytesSent", "BaselineBytes", "Deviation", "TopDestination", "Confidence"},
			"Verify the application is expected to upload this much."},

		// ---------------------------------------------------------------- 5000-5999
		Definition{NewExternalDestination, "NEW_EXTERNAL_DESTINATION", Info, CatSecurity,
			"A previously unseen external destination was contacted.",
			"A remote address/port pair with no prior history was observed.",
			[]string{"Destination", "RemotePort", "Protocol", "Process", "PID", "ReverseDNS", "ASN", "Organization", "Country"},
			"Informational. Most new destinations are benign."},
		Definition{RareDestinationContact, "RARE_DESTINATION_CONTACT", Notice, CatSecurity,
			"A destination contacted very rarely in the past was contacted again.",
			"Destination frequency is below the rarity percentile over the history window.",
			[]string{"Destination", "Frequency", "FirstSeen", "LastSeen", "Process", "ASN", "Country"},
			"Context only; combine with volume and threat-intel signals."},
		Definition{UnexpectedDestPort, "UNEXPECTED_DESTINATION_PORT", Notice, CatSecurity,
			"An outbound connection used a port outside the normal profile.",
			"Remote port not in the learned port profile and not in the configured expected set.",
			[]string{"Destination", "RemotePort", "Protocol", "Process", "PID", "PortProfile"},
			"Verify the application legitimately uses this port."},
		Definition{RapidDestinationFanout, "RAPID_DESTINATION_FANOUT", Warning, CatSecurity,
			"Many distinct external destinations were contacted in a short window.",
			"Distinct remote addresses within the fanout window exceeded the threshold.",
			[]string{"DistinctDestinations", "Window", "Process", "PID", "TopPorts", "Confidence"},
			"Possible scanning, peer-to-peer, or a crawler. Verify the process."},
		Definition{KnownMaliciousDest, "KNOWN_MALICIOUS_DESTINATION", Error, CatSecurity,
			"A connection matched a high-confidence indicator in local threat intelligence.",
			"Remote IP/CIDR matched an imported indicator whose confidence is High.",
			[]string{"RemoteIP", "RemotePort", "Protocol", "Process", "PID", "ExecutablePath", "User", "ThreatSource", "Indicator", "Confidence", "FeedUpdated", "BytesSent", "BytesReceived"},
			"Investigate the process. iPulse does not block traffic; blocking is an operator decision."},
		Definition{ThreatIntelligenceMatch, "THREAT_INTELLIGENCE_MATCH", Warning, CatSecurity,
			"A connection matched local threat intelligence.",
			"Remote IP, CIDR or domain matched an imported indicator.",
			[]string{"Process", "PID", "RemoteIP", "RemotePort", "ThreatSource", "Indicator", "IndicatorType", "Confidence", "FeedUpdated"},
			"Confirm the indicator is still valid; feeds carry false positives."},
		Definition{MaliciousDomainConn, "MALICIOUS_DOMAIN_CONNECTION", Warning, CatSecurity,
			"A resolved or reverse-resolved domain matched a domain blocklist.",
			"Domain observed via DNS monitoring or reverse DNS matched an imported domain indicator.",
			[]string{"Domain", "RemoteIP", "Process", "PID", "ThreatSource", "Indicator", "Confidence"},
			"As above."},
		Definition{ThreatFeedImported, "THREAT_FEED_IMPORTED", Info, CatSecurity,
			"A threat-intelligence feed was imported.",
			"Scheduled or manual feed import completed.",
			[]string{"Source", "Format", "Indicators", "Added", "Updated", "Removed", "Duration", "Confidence"},
			"None."},
		Definition{ThreatFeedImportFailed, "THREAT_FEED_IMPORT_FAILED", Warning, CatSecurity,
			"A threat-intelligence feed could not be imported.",
			"Fetch, parse or validation failure.",
			[]string{"Source", "Format", "Error", "LastSuccess"},
			"Check the feed URL/path and format. Existing indicators are retained."},
		Definition{InternalHostSweep, "INTERNAL_HOST_SWEEP", Warning, CatSecurity,
			"Possible host-sweep behaviour toward the local network.",
			"Connections to more distinct private hosts than the configured threshold within the window.",
			[]string{"DistinctHosts", "Window", "Process", "PID", "Ports", "Subnets", "FailedConnections", "Confidence", "Interpretation"},
			"Possible lateral scanning behaviour. Verify whether the process is an approved scanner or management tool."},
		Definition{PossiblePortScan, "POSSIBLE_PORT_SCAN", Warning, CatSecurity,
			"Possible port-scanning behaviour toward one or more hosts.",
			"Connections to more distinct ports on a host than the configured threshold within the window, or sequential port progression.",
			[]string{"TargetHost", "DistinctPorts", "Window", "Sequential", "Process", "PID", "FailedConnections", "Confidence", "Interpretation"},
			"Possible scanning behaviour, not confirmed compromise. Verify the process."},
		Definition{AbnormalLateralConns, "ABNORMAL_LATERAL_CONNECTIONS", Notice, CatSecurity,
			"Internal connection behaviour is inconsistent with the learned baseline.",
			"Internal connection count or distinct-peer count exceeded the baseline for this time bucket.",
			[]string{"DistinctHosts", "Connections", "BaselineHosts", "Deviation", "Bucket", "Process", "Confidence", "Interpretation"},
			"Context signal; combine with sweep/scan events."},
		Definition{RepeatedInternalFailures, "REPEATED_INTERNAL_CONNECTION_FAILURES", Notice, CatSecurity,
			"Many failed connection attempts to internal hosts.",
			"SYN_SENT or refused internal connections above the threshold within the window.",
			[]string{"FailedAttempts", "DistinctHosts", "Window", "Ports", "Process", "PID", "Confidence", "Interpretation"},
			"Often a misconfigured client; can also indicate discovery activity."},
		Definition{RemoteAdminProtoSweep, "REMOTE_ADMIN_PROTOCOL_SWEEP", Warning, CatSecurity,
			"Possible sweep of remote-administration ports across internal hosts.",
			"Connections to SMB/RDP/SSH/WinRM/VNC ports on more distinct internal hosts than the threshold.",
			[]string{"Protocols", "DistinctHosts", "Ports", "Window", "Process", "PID", "FailedConnections", "Confidence", "Interpretation"},
			"Possible lateral movement reconnaissance. Verify against approved management tooling."},

		// ---------------------------------------------------------------- 6000-6999
		Definition{DNSResolutionOK, "DNS_RESOLUTION_OK", Debug, CatNameRouting,
			"A DNS probe succeeded.",
			"The DNS interval elapsed and resolution succeeded.",
			[]string{"Name", "Server", "ResponseTime", "Answers", "Protocol"},
			"None."},
		Definition{DNSResolutionFailed, "DNS_RESOLUTION_FAILED", Warning, CatNameRouting,
			"A DNS probe failed.",
			"Resolution failed or timed out on all configured resolvers.",
			[]string{"Name", "Server", "Error", "ServersTested", "ServersFailed", "Timeout"},
			"Check the resolver and whether the network path is up."},
		Definition{DNSServerChanged, "DNS_SERVER_CHANGED", Notice, CatNameRouting,
			"The system's configured resolvers changed.",
			"The resolver list differs from the previous observation.",
			[]string{"Previous", "Current", "Interface", "VPNActive"},
			"Expected after DHCP renewal or VPN connect; unexpected changes are worth review."},
		Definition{DNSSlowResponse, "DNS_SLOW_RESPONSE", Warning, CatNameRouting,
			"DNS responses exceeded the configured latency threshold.",
			"Response time above alerts.dns_slow_ms for the required persistence.",
			[]string{"Name", "Server", "ResponseTime", "Threshold", "BaselineDNS"},
			"Try an alternate resolver."},
		Definition{DNSPartialFailure, "DNS_PARTIAL_FAILURE", Notice, CatNameRouting,
			"Some resolvers answered and others did not.",
			"Mixed per-resolver results in one probe cycle.",
			[]string{"ServersTested", "ServersFailed", "FailedServers", "WorkingServers", "Name"},
			"Consider removing the failing resolver from the configuration."},
		Definition{PublicIPChanged, "PUBLIC_IP_CHANGED", Notice, CatNameRouting,
			"The public IP address changed.",
			"A public IP probe returned a different address than the stored one.",
			[]string{"Family", "PreviousIP", "NewIP", "Interface", "ASN", "Organization", "Country", "VPNActive", "Provider", "CGNAT"},
			"Normal for dynamic addressing. Not treated as a security incident on its own."},
		Definition{PublicIPUnavailable, "PUBLIC_IP_UNAVAILABLE", Warning, CatNameRouting,
			"The public IP could not be determined.",
			"All configured public IP providers failed.",
			[]string{"Family", "ProvidersTested", "Errors"},
			"Usually a symptom of an outage rather than a problem itself."},
		Definition{ISPASNChanged, "ISP_ASN_CHANGED", Notice, CatNameRouting,
			"The autonomous system serving this connection changed.",
			"ASN for the current public IP differs from the previous observation.",
			[]string{"PreviousASN", "NewASN", "PreviousOrg", "NewOrg", "PublicIP", "VPNActive"},
			"Expected on VPN connect, ISP failover or a network change."},
		Definition{VPNStateChanged, "VPN_STATE_CHANGED", Notice, CatNameRouting,
			"A VPN or tunnel interface became active or inactive.",
			"Tunnel interface appeared/disappeared, or the default route moved to a tunnel.",
			[]string{"VPNActive", "Interface", "InterfaceType", "DefaultRouteVia", "PublicIP", "PreviousPublicIP", "DNSServers"},
			"Explains public IP, DNS and route changes that follow."},
		Definition{PossibleCGNAT, "POSSIBLE_CGNAT_DETECTED", Info, CatNameRouting,
			"The connection appears to be behind carrier-grade NAT.",
			"The WAN-side address is in 100.64.0.0/10, or the observed public IP differs from every local address while no tunnel is active.",
			[]string{"PublicIP", "LocalWANAddress", "Evidence"},
			"Inbound connections will not work; relevant when diagnosing port forwarding."},
		Definition{VPNRoutingChange, "VPN_ROUTING_CHANGE", Notice, CatNameRouting,
			"A VPN or tunnel change moved the default route, the public address and the resolvers together.",
			"Correlation rule: a tunnel or default-route change accompanied by a public IP, ASN or resolver change.",
			[]string{"PublicIP", "PreviousPublicIP", "Interface", "DefaultRouteVia", "ASN", "Evidence", "ProbableCause"},
			"None. This groups what would otherwise be several separate notices into one explanation."},
		Definition{RouteChanged, "ROUTE_CHANGED", Notice, CatNameRouting,
			"A monitored path changed significantly.",
			"Hop set for a monitored destination differs beyond the configured tolerance.",
			[]string{"Destination", "PreviousHops", "CurrentHops", "ChangedAt", "PreviousPath", "CurrentPath", "VPNActive"},
			"Normal ISP re-routing is common; correlate with latency changes."},
		Definition{DefaultGatewayChange, "DEFAULT_GATEWAY_CHANGED", Notice, CatNameRouting,
			"The default gateway changed.",
			"The default route's next hop or interface changed.",
			[]string{"PreviousGateway", "NewGateway", "PreviousInterface", "NewInterface", "Metric", "VPNActive"},
			"Expected on network change, failover or VPN connect."},
		Definition{HopCountChanged, "HOP_COUNT_CHANGED", Info, CatNameRouting,
			"The number of hops to a monitored destination changed.",
			"Hop count differs from the previous measurement.",
			[]string{"Destination", "PreviousHopCount", "CurrentHopCount", "Delta"},
			"None."},
		Definition{TracerouteCompleted, "TRACEROUTE_COMPLETED", Debug, CatNameRouting,
			"A path measurement completed.",
			"The route monitor interval elapsed, or a manual traceroute was requested.",
			[]string{"Destination", "Hops", "Duration", "Path", "Method"},
			"None."},
		Definition{TracerouteUnavail, "TRACEROUTE_UNAVAILABLE", Notice, CatNameRouting,
			"Path measurement is unavailable on this host.",
			"Raw/datagram ICMP sockets are not permitted for this process.",
			[]string{"Reason", "Platform", "Remedy"},
			"Grant CAP_NET_RAW on Linux, or run elevated on Windows, to enable path measurement."},

		// ---------------------------------------------------------------- 7000-7999
		Definition{InterfaceUp, "INTERFACE_UP", Notice, CatInterface,
			"A network interface came up.",
			"Interface operational state transitioned to up.",
			[]string{"Interface", "Type", "MAC", "Addresses", "MTU", "LinkSpeed"},
			"None."},
		Definition{InterfaceDown, "INTERFACE_DOWN", Error, CatInterface,
			"A network interface went down.",
			"Interface operational state transitioned to down or lost carrier.",
			[]string{"Interface", "Type", "PreviousAddresses", "WasDefaultRoute"},
			"If this was the default-route interface, expect an outage record."},
		Definition{InterfaceChanged, "INTERFACE_CHANGED", Notice, CatInterface,
			"The interface carrying the default route changed.",
			"The default-route interface differs from the previous observation.",
			[]string{"Previous", "Current", "PreviousType", "CurrentType", "VPNActive"},
			"Expected on Wi-Fi/Ethernet handover or VPN connect."},
		Definition{IPAddressChanged, "IP_ADDRESS_CHANGED", Notice, CatInterface,
			"A local IP address changed.",
			"Address set on an interface differs from the previous observation.",
			[]string{"Interface", "Previous", "Current", "Family", "Scope"},
			"Expected after DHCP renewal."},
		Definition{LinkSpeedChanged, "LINK_SPEED_CHANGED", Info, CatInterface,
			"Negotiated link speed changed.",
			"Reported interface speed differs from the previous observation.",
			[]string{"Interface", "PreviousSpeed", "CurrentSpeed", "Duplex"},
			"A drop to a lower rate can indicate a cabling or driver problem."},
		Definition{InterfaceErrorsRising, "INTERFACE_ERRORS_RISING", Warning, CatInterface,
			"Interface error or drop counters are increasing.",
			"Delta of errors/drops per sample above the configured threshold.",
			[]string{"Interface", "RxErrors", "TxErrors", "RxDropped", "TxDropped", "Window", "ErrorRate"},
			"Usually physical: cable, port, driver or radio interference."},
		Definition{WiFiConnected, "WIFI_CONNECTED", Info, CatInterface,
			"A wireless interface associated with a network.",
			"Wi-Fi association observed.",
			[]string{"Interface", "SSID", "BSSID", "Signal", "SignalPercent", "LinkSpeed", "Frequency", "Channel", "Band"},
			"None. No credentials are collected."},
		Definition{WiFiDisconnected, "WIFI_DISCONNECTED", Warning, CatInterface,
			"A wireless interface lost its association.",
			"Wi-Fi association lost.",
			[]string{"Interface", "PreviousSSID", "LastSignal", "Duration"},
			"None."},
		Definition{WiFiSignalDegraded, "WIFI_SIGNAL_DEGRADED", Warning, CatInterface,
			"Wireless signal strength dropped below the configured threshold.",
			"RSSI below wifi.weak_signal_dbm for the required persistence.",
			[]string{"Interface", "SSID", "Signal", "SignalPercent", "BaselineSignal", "Threshold", "LinkSpeed", "PacketLoss"},
			"Weak signal explains latency and loss that would otherwise look like an ISP fault."},
		Definition{WiFiSSIDChanged, "WIFI_SSID_CHANGED", Notice, CatInterface,
			"The wireless network changed.",
			"Associated SSID or BSSID differs from the previous observation.",
			[]string{"Interface", "PreviousSSID", "CurrentSSID", "PreviousBSSID", "CurrentBSSID", "Signal"},
			"Roaming between APs is normal."},
		Definition{WiFiLinkSpeedDegraded, "WIFI_LINK_SPEED_DEGRADED", Warning, CatInterface,
			"Wireless link rate dropped well below its baseline.",
			"Link rate below the baseline band for the required persistence.",
			[]string{"Interface", "SSID", "LinkSpeed", "BaselineLinkSpeed", "Deviation", "Signal", "Channel"},
			"Interference or distance; consider changing channel or band."},
		Definition{WiFiMonitoringUnavail, "WIFI_MONITORING_UNAVAILABLE", Debug, CatInterface,
			"Wireless telemetry is unavailable on this host.",
			"No wireless interface, or the platform API is unavailable/not permitted.",
			[]string{"Reason", "Platform"},
			"Only relevant if this host does use Wi-Fi."},

		// ---------------------------------------------------------------- 8000-8999
		Definition{AgentStarted, "AGENT_STARTED", Notice, CatService,
			"The iPulse agent started.",
			"Service or foreground start-up completed.",
			[]string{"Version", "Commit", "BuildDate", "Platform", "PID", "User", "Elevated", "ConfigPath", "DataDir", "Mode"},
			"None."},
		Definition{AgentStopped, "AGENT_STOPPED", Notice, CatService,
			"The iPulse agent stopped.",
			"Shutdown signal received and shutdown completed.",
			[]string{"Reason", "Uptime", "Signal", "EventsLogged", "MeasurementsStored"},
			"None."},
		Definition{ConfigLoaded, "CONFIG_LOADED", Info, CatService,
			"Configuration was loaded and validated.",
			"Start-up, or a successful reload.",
			[]string{"Path", "Source", "Warnings", "Checksum"},
			"None."},
		Definition{ConfigReloaded, "CONFIG_RELOADED", Notice, CatService,
			"Configuration was reloaded at runtime.",
			"SIGHUP on Linux, or a service control request on Windows.",
			[]string{"Path", "Changed", "AppliedImmediately", "RequiresRestart"},
			"Some settings (dashboard bind address, database path) need a restart; they are listed."},
		Definition{ConfigInvalid, "CONFIG_INVALID", Error, CatService,
			"Configuration failed validation and was not applied.",
			"Validation errors during load or reload.",
			[]string{"Path", "Errors", "UsingPrevious"},
			"Fix the listed errors; the previous valid configuration stays active."},
		Definition{ServiceInstalled, "SERVICE_INSTALLED", Notice, CatService,
			"The iPulse service was installed.",
			"`ipulse service install` completed.",
			[]string{"ServiceName", "DisplayName", "ExecPath", "StartType", "User"},
			"None."},
		Definition{ServiceRemoved, "SERVICE_REMOVED", Notice, CatService,
			"The iPulse service was removed.",
			"`ipulse service uninstall` completed.",
			[]string{"ServiceName", "DataRetained"},
			"None."},
		Definition{DatabaseOpened, "DATABASE_OPENED", Info, CatService,
			"The local database was opened.",
			"Start-up.",
			[]string{"Path", "SchemaVersion", "Migrations", "SizeBytes", "Journal"},
			"None."},
		Definition{RetentionCompleted, "RETENTION_PRUNE_COMPLETED", Info, CatService,
			"Retention pruning finished.",
			"The retention interval elapsed.",
			[]string{"RowsDeleted", "RowsRolledUp", "Tables", "Duration", "SizeBefore", "SizeAfter", "Reclaimed"},
			"None."},
		Definition{LogRotated, "LOG_ROTATED", Info, CatService,
			"A log file was rotated.",
			"Log file reached logging.max_file_mb, or a scheduled daily rotation occurred.",
			[]string{"File", "Archive", "SizeBytes", "Compressed", "ArchivesRetained", "ArchivesDeleted"},
			"None."},
		Definition{APIStarted, "API_STARTED", Info, CatService,
			"The REST API and dashboard are listening.",
			"Start-up with dashboard.enabled true.",
			[]string{"Address", "Port", "TLS", "AuthRequired", "Loopback"},
			"None."},
		Definition{APIStopped, "API_STOPPED", Info, CatService,
			"The REST API stopped listening.",
			"Shutdown, or a listener error.",
			[]string{"Reason", "Requests", "Duration"},
			"None."},
		Definition{SchedulerTaskSkip, "SCHEDULER_TASK_SKIPPED", Debug, CatService,
			"A scheduled task was skipped because the previous run was still active.",
			"Overlapping tick for a single-flight task.",
			[]string{"Task", "Interval", "RunningFor"},
			"Repeated skips mean the interval is too aggressive for this host or link."},
		Definition{PrivilegeLimited, "PRIVILEGE_LIMITED", Notice, CatService,
			"A monitoring function is degraded because of insufficient privileges.",
			"A platform capability probe failed at start-up.",
			[]string{"Feature", "Required", "Platform", "Fallback", "Impact"},
			"See docs/security.md for the privilege matrix; the fallback in use is named."},
		Definition{BaselineEstablished, "BASELINE_ESTABLISHED", Info, CatService,
			"A metric baseline became usable.",
			"A metric/time bucket reached baseline.min_observations.",
			[]string{"Metric", "Bucket", "Observations", "Mean", "Median", "P95", "StdDev"},
			"None. Detection for that metric and bucket starts now."},
		Definition{ManualTestRequested, "MANUAL_TEST_REQUESTED", Info, CatService,
			"A test was requested manually.",
			"CLI or dashboard/API request.",
			[]string{"Test", "Source", "Client", "Parameters"},
			"None."},

		// ---------------------------------------------------------------- 9000-9999
		Definition{InternalError, "INTERNAL_ERROR", Error, CatInternal,
			"An unexpected internal error occurred.",
			"An error path with no more specific event.",
			[]string{"Component", "Operation", "Error"},
			"Report with the surrounding log context."},
		Definition{DatabaseError, "DATABASE_ERROR", Error, CatInternal,
			"A database operation failed.",
			"SQLite returned an error.",
			[]string{"Operation", "Table", "Error", "Retries"},
			"Check disk space and file permissions on the data directory."},
		Definition{CollectorError, "COLLECTOR_ERROR", Warning, CatInternal,
			"A collector failed to gather data.",
			"A platform call or parse failed.",
			[]string{"Collector", "Error", "Consecutive", "Platform"},
			"Isolated failures are tolerated; repeated ones indicate a platform problem."},
		Definition{ProbeError, "PROBE_ERROR", Warning, CatInternal,
			"A network probe failed for a reason other than connectivity loss.",
			"Socket, TLS or protocol error not attributable to an outage.",
			[]string{"Probe", "Target", "Error", "Consecutive"},
			"Check the probe target configuration."},
		Definition{PanicRecovered, "PANIC_RECOVERED", Critical, CatInternal,
			"A panic was recovered; the agent kept running.",
			"A goroutine panicked and the supervisor recovered it.",
			[]string{"Component", "Panic", "Stack"},
			"This is a bug. Please report it with the stack field."},
		Definition{LogSinkError, "LOG_SINK_ERROR", Error, CatInternal,
			"A log sink failed to write.",
			"Filesystem, journald or Event Log write failure.",
			[]string{"Sink", "Error", "Dropped"},
			"Check disk space and permissions; other sinks continue."},
		Definition{TaskTimeout, "TASK_TIMEOUT", Warning, CatInternal,
			"A scheduled task exceeded its timeout and was cancelled.",
			"Task context deadline exceeded.",
			[]string{"Task", "Timeout", "Interval"},
			"Frequent timeouts suggest an unreachable target or too tight a timeout."},
		Definition{ConfigWatchErr, "CONFIG_WATCH_ERROR", Warning, CatInternal,
			"The configuration file could not be watched for changes.",
			"Watcher setup or read failure.",
			[]string{"Path", "Error"},
			"Reload manually with SIGHUP or a service restart."},
	)
}

// Markdown renders the whole catalog as the event-catalog document body.
func Markdown() string {
	var b strings.Builder
	b.WriteString("# iPulse Event Catalog\n\n")
	b.WriteString("This file is generated from the event catalog in `internal/events/catalog_defs.go`.\n")
	b.WriteString("Regenerate with `ipulse events catalog --markdown > docs/event-catalog.md`.\n\n")
	b.WriteString("Every iPulse event has a stable numeric ID rendered as `IPULSE-<id>` and a stable\n")
	b.WriteString("machine name. Once published, an ID never changes meaning.\n\n")
	b.WriteString("## Severity levels\n\n")
	b.WriteString("| Level | Log label | Syslog | Meaning |\n|---|---|---|---|\n")
	b.WriteString("| DEBUG | `DEBUG` | 7 | Routine measurement detail; off by default. |\n")
	b.WriteString("| INFO | `INFO` | 6 | Normal significant activity, such as a completed speed test. |\n")
	b.WriteString("| NOTICE | `NOTICE` | 5 | A noteworthy state change that is not a fault. |\n")
	b.WriteString("| WARNING | `WARN` | 4 | Degradation or a suspicious observation worth review. |\n")
	b.WriteString("| ERROR | `ERROR` | 3 | A real failure: outage, confirmed loss of a layer. |\n")
	b.WriteString("| CRITICAL | `CRIT` | 2 | Local failure that stops monitoring, or a recovered panic. |\n\n")
	b.WriteString("## Reserved ID ranges\n\n")
	b.WriteString("| Range | Category |\n|---|---|\n")
	for _, c := range AllCategories() {
		lo, hi := CategoryRange(c)
		fmt.Fprintf(&b, "| %d-%d | %s |\n", lo, hi-1, c)
	}
	b.WriteString("\n## Events\n")
	current := Category("")
	for _, d := range All() {
		if d.Category != current {
			current = d.Category
			lo, hi := CategoryRange(current)
			fmt.Fprintf(&b, "\n### %s (%d-%d)\n", current, lo, hi-1)
		}
		fmt.Fprintf(&b, "\n#### IPULSE-%d %s\n\n", d.Code, d.Name)
		fmt.Fprintf(&b, "- **Severity:** %s\n", d.Severity)
		fmt.Fprintf(&b, "- **Meaning:** %s\n", d.Summary)
		fmt.Fprintf(&b, "- **Trigger:** %s\n", d.Trigger)
		if len(d.Fields) > 0 {
			fmt.Fprintf(&b, "- **Fields:** %s\n", "`"+strings.Join(d.Fields, "`, `")+"`")
		}
		fmt.Fprintf(&b, "- **Operator action:** %s\n", d.Action)
	}
	b.WriteString("\n---\n\nTotal events: ")
	fmt.Fprintf(&b, "%d\n", len(catalog))
	return b.String()
}
