#!/usr/bin/env bash
#
# Build a Debian package for iPulse.
#
#   packaging/deb/build.sh [amd64|arm64|armhf]
#
# The package is assembled with ar and tar rather than dpkg-deb, so it can be built on
# any host - including one that has never seen a Debian tool. dpkg-deb is used when it
# is available, because it validates the result.

set -euo pipefail
cd "$(dirname "$0")/../.."

ARCH="${1:-amd64}"
VERSION="$(cat VERSION 2>/dev/null || echo 1.0.0)"
PKG="ipulse"
MAINTAINER="iPulse Authors <ipulse@example.invalid>"

case "$ARCH" in
  amd64) GOARCH=amd64 ;;
  arm64) GOARCH=arm64 ;;
  armhf) GOARCH=arm ;;
  *) echo "unsupported architecture: $ARCH" >&2; exit 2 ;;
esac

BINARY="dist/linux-${GOARCH}/ipulse"
[ -x "$BINARY" ] || { echo "missing $BINARY; run scripts/build.sh --all first" >&2; exit 1; }

BUILD="$(mktemp -d)"
trap 'rm -rf "$BUILD"' EXIT

# ---- payload --------------------------------------------------------------
install -d -m 0755 "$BUILD/root/usr/bin"
install -m 0755 "$BINARY" "$BUILD/root/usr/bin/ipulse"

install -d -m 0755 "$BUILD/root/usr/share/doc/${PKG}"
install -m 0644 README.md LICENSE CHANGELOG.md "$BUILD/root/usr/share/doc/${PKG}/" 2>/dev/null || true
install -d -m 0755 "$BUILD/root/usr/share/doc/${PKG}/docs"
install -m 0644 docs/*.md "$BUILD/root/usr/share/doc/${PKG}/docs/" 2>/dev/null || true

# The configuration ships as a conffile so dpkg preserves local edits on upgrade.
install -d -m 0755 "$BUILD/root/etc/ipulse"
install -m 0640 configs/ipulse.yaml "$BUILD/root/etc/ipulse/ipulse.yaml"

# The unit file is generated by the binary itself, so the packaged unit and the one
# `ipulse service install` writes can never drift apart.
install -d -m 0755 "$BUILD/root/lib/systemd/system"
./bin/ipulse service unit > "$BUILD/root/lib/systemd/system/ipulse.service" 2>/dev/null \
  || cp packaging/deb/ipulse.service "$BUILD/root/lib/systemd/system/ipulse.service"
chmod 0644 "$BUILD/root/lib/systemd/system/ipulse.service"

INSTALLED_SIZE=$(du -sk "$BUILD/root" | cut -f1)

# ---- control --------------------------------------------------------------
install -d -m 0755 "$BUILD/control"
cat > "$BUILD/control/control" <<CONTROL
Package: ${PKG}
Version: ${VERSION}
Section: net
Priority: optional
Architecture: ${ARCH}
Maintainer: ${MAINTAINER}
Installed-Size: ${INSTALLED_SIZE}
Depends: adduser
Recommends: systemd
Homepage: https://github.com/ipulse/ipulse
Description: Internet connection monitoring and network observability agent
 iPulse continuously measures Internet availability, connection quality and speed,
 and analyses local and external network activity to identify performance problems,
 outages, unusual traffic and suspicious connections.
 .
 Everything is stored locally in SQLite. There is no cloud account, no telemetry and
 no payload capture: iPulse collects metadata only.
CONTROL

cat > "$BUILD/control/conffiles" <<'CONFFILES'
/etc/ipulse/ipulse.yaml
CONFFILES

cat > "$BUILD/control/preinst" <<'PREINST'
#!/bin/sh
set -e
# A dedicated unprivileged account owns the agent's files and its process.
if ! id -u ipulse >/dev/null 2>&1; then
    adduser --system --group --no-create-home --home /var/lib/ipulse \
            --gecos "iPulse monitoring agent" ipulse >/dev/null 2>&1 || \
    useradd --system --no-create-home --home-dir /var/lib/ipulse \
            --shell /usr/sbin/nologin --comment "iPulse monitoring agent" ipulse
fi
PREINST

cat > "$BUILD/control/postinst" <<'POSTINST'
#!/bin/sh
set -e

case "$1" in
  configure)
    # The data directory holds connection metadata, so it is not world-readable.
    install -d -m 0750 -o ipulse -g ipulse /var/lib/ipulse
    install -d -m 0750 -o ipulse -g ipulse /var/log/ipulse
    chown root:ipulse /etc/ipulse /etc/ipulse/ipulse.yaml 2>/dev/null || true
    chmod 0750 /etc/ipulse 2>/dev/null || true
    chmod 0640 /etc/ipulse/ipulse.yaml 2>/dev/null || true

    # Refuse to start with a configuration that will not load.
    if ! /usr/bin/ipulse config validate --config /etc/ipulse/ipulse.yaml >/dev/null 2>&1; then
        echo "iPulse: /etc/ipulse/ipulse.yaml is not valid; the service was not started." >&2
        echo "iPulse: run 'ipulse config validate' to see the problems." >&2
        exit 0
    fi

    if [ -d /run/systemd/system ]; then
        systemctl daemon-reload >/dev/null 2>&1 || true
        systemctl enable ipulse.service >/dev/null 2>&1 || true
        systemctl restart ipulse.service >/dev/null 2>&1 || true
        echo "iPulse is running. Dashboard: http://127.0.0.1:8750"
        echo "Set your ISP plan in /etc/ipulse/ipulse.yaml (speed_test.expected_*_mbps)."
    fi
    ;;
esac
POSTINST

cat > "$BUILD/control/prerm" <<'PRERM'
#!/bin/sh
set -e
if [ -d /run/systemd/system ]; then
    systemctl stop ipulse.service >/dev/null 2>&1 || true
    systemctl disable ipulse.service >/dev/null 2>&1 || true
fi
PRERM

cat > "$BUILD/control/postrm" <<'POSTRM'
#!/bin/sh
set -e

case "$1" in
  purge)
    # Only a purge removes measurements: an ordinary removal is often a reinstall, and
    # months of history should not disappear without being asked for.
    rm -rf /var/lib/ipulse /var/log/ipulse /etc/ipulse
    if id -u ipulse >/dev/null 2>&1; then
        deluser --system ipulse >/dev/null 2>&1 || userdel ipulse >/dev/null 2>&1 || true
    fi
    ;;
esac

if [ -d /run/systemd/system ]; then
    systemctl daemon-reload >/dev/null 2>&1 || true
fi
POSTRM

chmod 0755 "$BUILD/control/preinst" "$BUILD/control/postinst" \
           "$BUILD/control/prerm" "$BUILD/control/postrm"

# md5sums let dpkg detect locally modified files.
( cd "$BUILD/root" && find . -type f ! -path './etc/*' -printf '%P\n' | sort | \
  xargs -r md5sum > "$BUILD/control/md5sums" ) 2>/dev/null || true

# ---- assemble -------------------------------------------------------------
mkdir -p dist
OUTPUT="dist/${PKG}_${VERSION}_${ARCH}.deb"

if command -v dpkg-deb >/dev/null 2>&1; then
  STAGE="$BUILD/stage"
  mkdir -p "$STAGE/DEBIAN"
  cp -a "$BUILD/root/." "$STAGE/"
  cp -a "$BUILD/control/." "$STAGE/DEBIAN/"
  dpkg-deb --build --root-owner-group "$STAGE" "$OUTPUT" >/dev/null
else
  # Hand-assembled: a .deb is an ar archive of three members, in this order.
  ( cd "$BUILD/control" && tar czf ../control.tar.gz --owner=0 --group=0 . )
  ( cd "$BUILD/root" && tar czf ../data.tar.gz --owner=0 --group=0 . )
  echo "2.0" > "$BUILD/debian-binary"
  ( cd "$BUILD" && ar rc "$OLDPWD/$OUTPUT" debian-binary control.tar.gz data.tar.gz )
fi

echo "built $OUTPUT"
ls -lh "$OUTPUT" | awk '{print "  size " $5}'
if command -v dpkg-deb >/dev/null 2>&1; then
  dpkg-deb --info "$OUTPUT" | sed 's/^/  /'
fi
